// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0VqmgX9VzwK0X1THahopjxyssaYpqbwU',
    appId: '1:647124052824:web:b789c3447f09d2d6f8132d',
    messagingSenderId: '647124052824',
    projectId: 'test-map-3dfef',
    authDomain: 'test-map-3dfef.firebaseapp.com',
    storageBucket: 'test-map-3dfef.appspot.com',
    measurementId: 'G-DX8KF00R33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4yhuIJcsBpt1juW8RsrUbSZQ1nw-Gxzo',
    appId: '1:647124052824:android:126319f083acfdb2f8132d',
    messagingSenderId: '647124052824',
    projectId: 'test-map-3dfef',
    storageBucket: 'test-map-3dfef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoromwunTE1NWitIGAu68bcefG3gEv2Ps',
    appId: '1:647124052824:ios:8f897b5dafda78e8f8132d',
    messagingSenderId: '647124052824',
    projectId: 'test-map-3dfef',
    storageBucket: 'test-map-3dfef.appspot.com',
    iosBundleId: 'com.example.testMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoromwunTE1NWitIGAu68bcefG3gEv2Ps',
    appId: '1:647124052824:ios:06056c5885d21687f8132d',
    messagingSenderId: '647124052824',
    projectId: 'test-map-3dfef',
    storageBucket: 'test-map-3dfef.appspot.com',
    iosBundleId: 'com.example.testMap.RunnerTests',
  );
}
